// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  graphqlEndpoint:
    'https://p6d5h4dngffybgwq47jish5rlm.appsync-api.ap-northeast-1.amazonaws.com/graphql',
  region: 'ap-northeast-1',
  authenticationType: 'API_KEY',
  apiKey: 'da2-wlpm3dlgancvjd4gxw2sfyknfa',
};

export default awsmobile;
